### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by JCBurnside** [OpenPrograms/Gopher-Programs#10]
I just downloaded this I have no idea how to install it.  I tried running the gmltest.lua in minecraft but it returns "attempt to index local 'gml' (a boolean value)"

**Comment by GopherAtl** [comment]
Sorryy for slow response, probably too late to be useful but will answer anyway.

I've not played with mc/oc in a long time, and I'm blanking on the name, but there is (used to be?) a floppy in the creative menus with a package manager that will auto-install this and many other things from OpenPrograms... you could find it in dungeon loot I think in survival as well? That is gonna be your best bet, I didn't write a separate installer for it specifically.

**Comment by bbgott** [comment]
I believe the disk you are referring to is oppm. I think you can also craft it with a blank floppy and an interweb, if I recall correctly.
