### ISSUE TITLE
Scrollbar misaligned with listbox

### ISSUE THREAD

**Issue by bbgott** [OpenPrograms/Gopher-Programs#12]
This is a truly amazing project.  I noticed when running the gmltest program on the latest build of OpenComputers for Minecraft 1.7.10, the scrollbar is misaligned on the side of the listbox.

Environment:
OC 1.5.17.33
MC 1.7.10
Forge 10.13.4.1448

**Comment by Krutoy242** [comment]
Thanks for report and sorry for long response =)

It was my mistake, finally fixed.
Follow the link, need to change only one line.
https://github.com/OpenPrograms/Gopher-Programs/pull/13/files

**Comment by bbgott** [comment]
Thanks for the update!
